### ISSUE TITLE
Untextured Better Animals Skins

### ISSUE THREAD

**Issue by BeanZephyron** [Budschie/BudschieMorphMod#9]
First of all, I wanted to thank you for giving Forge a morph mod! I absolutely love it! I did, however, notice that whenever I kill a Better Animals Plus animal and try to morph into it, the skins are untextured. I was unsure of what exactly was causing it. This is with the newest version.

**Comment by Budschie** [comment]
Alright. This issue should be fixed soon, as I could identify and solve the problem (which was that some animals in this mod have a "VariantId" (which essentially is like a skin). This very VariantId was ignored by my mod (because I didn't told my mod to remember this field when creating a morph). This lead to the purple black texture.) This issue will still arise when morphing into a mob with the /morph command (as you would have to specify the NBT data here so that it works), but when it comes to survival mode, this issue should be fixed in the next release.

**Comment by Budschie** [comment]
Alright, the release is out and should fix these issues (if you kill the entity and morph into it with the morph menu, textures should be there).

**Comment by BeanZephyron** [comment]
Thank you so much! The textures are working great! I did find another issue that seems to happen only when I kill a Better Animals Plus octopus. The game crashes, stating that it cannot create a morph for the entity. Do I need to update my Forge, or is this an issue within the mod?

**Comment by BeanZephyron** [comment]
Sorry about the wait, by the way.

**Comment by Budschie** [comment]
Well, I can't say for sure what the issue might be, but I suspect that there might be some NBT tags that are being read in mandatorilly which are not present when the entity for the morph is created.

**Comment by BeanZephyron** [comment]
Would you like the crash log? I can send it to you if that will help. I tested it with the newest version of Forge, and I am still having issues.
